### PR TITLE
Added arcface model

### PR DESCRIPTION
**Pull request by abhinavs95**
Added ArcFace face recognition with the following artifacts:
* Model readme page with links to download ONNX model and dataset
* Training, inference, validation notebooks
* Additional scripts required by the notebooks
* Added link from main readme page

### CODE REVIEW

File: models/face_recognition/ArcFace/README.md [hunk 1]
```diff
@@ -0,0 +1,68 @@
+# ArcFace
+ArcFace is a CNN based model for face recognition which learns discriminative features of faces and produces embeddings for input face images. To enhance the discriminative power of softmax loss, a novel supervisor signal called additive angular margin (ArcFace) is used here as an additive term in the softmax loss. ArcFace can use a variety of CNN networks as its backend, each having different accuracy and performance. For each face image, the model produces a fixed length embedding vector corresponding to the face in the image. The vectors from face images of a single person have a higher similarity than that from different persons. Therefore, the model is primarily used for face recognition/verification. It can also be used in other applications like facial feature based clustering.
```
Comment (ankkhedia) [inline models/face_recognition/ArcFace/README.md]: Could you split this into two sections like one paragraph showing use case and other a little technical detail.

File: models/face_recognition/ArcFace/README.md [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+
+## Model
+The model LResNet100E-IR is an ArcFace model that uses ResNet100 as a backend with modified input and output layers.
+
+|Model        |ONNX Model  |LFW accuracy (%)|CFP-FF accuracy (%)|CFP-FP accuracy (%)|AgeDB-30 accuracy (%)|
+|-------------|:--------------|:--------------|:--------------|:--------------|:--------------|
+|LResNet100E-IR|    [248.9 MB](https://s3.amazonaws.com/onnx-model-zoo/arcface/resnet100/resnet100.onnx)     |99.77     | 99.83  |  94.21     | 97.87|
```
Comment (ankkhedia) [inline models/face_recognition/ArcFace/README.md]: Add a footnote to point to accuracy section where they are mentioned

File: models/face_recognition/ArcFace/README.md [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+The input to the model should preferably be images containing a single face in each image. There are no constraints on the size of the image. The example displayed in the inference notebook was done using jpeg images.
+
+### Preprocessing
+In order to input only face pixels into the network, all input images are passed through a pretrained face detection and alignment model, [MTCNN detector](https://kpzhang93.github.io/MTCNN_face_detection_alignment/index.html). The output of this model are landmark points and a bounding box corresponding to the face in the image. Using this output, the image is processed using affine transforms to generate the aligned face images which are input to the network.
+
+### Output
+The model outputs an embedding vector for the input face images. The size of the vector is tunable (512 for LResNet100E-IR).
+
+### Postprocessing
+The post-processing involves normalizing the output embedding vectors to have unit length.
```
Comment (ankkhedia) [inline models/face_recognition/ArcFace/README.md]: Can you elaborate a little bit more on post -processing in simple terms and add link to post-processing code.

File: models/face_recognition/ArcFace/mtcnn-model/det1-symbol.json [hunk 4]
```diff
@@ -0,0 +1,266 @@
+{
+  "nodes": [
+    {
+      "op": "null", 
+      "param": {},
```
[the remark this answers is not in the document]
Comment (ankkhedia) [reply models/face_recognition/ArcFace/mtcnn-model/det1-symbol.json]: If it is some retrained model, still add it to S3 and use it rather than putting it over here

File: models/face_recognition/ArcFace/mtcnn-model/det1.prototxt [hunk 5]
```diff
@@ -0,0 +1,177 @@
+name: "PNet"
```
Comment (ankkhedia) [inline models/face_recognition/ArcFace/mtcnn-model/det1.prototxt]: put in S3

File: models/face_recognition/ArcFace/mtcnn-model/det2-symbol.json [hunk 6]
```diff
@@ -0,0 +1,324 @@
+{
```
Comment (ankkhedia) [inline models/face_recognition/ArcFace/mtcnn-model/det2-symbol.json]: Put in S3 bucket

File: models/face_recognition/ArcFace/mtcnn-model/det2.prototxt [hunk 7]
```diff
@@ -0,0 +1,228 @@
+name: "RNet"
```
Comment (ankkhedia) [inline models/face_recognition/ArcFace/mtcnn-model/det2.prototxt]: S3 bucket

File: models/face_recognition/ArcFace/symbol_utils.py [hunk 8]
```diff
@@ -0,0 +1,136 @@
+import mxnet as mx
+
+def Conv(**kwargs):
+    #name = kwargs.get('name')
+    #_weight = mx.symbol.Variable(name+'_weight')
```
Comment (ankkhedia) [inline models/face_recognition/ArcFace/symbol_utils.py]: remove commented code and add more comments(description)

File: models/image_classification/squeezenet/README.md [hunk 9]
```diff
@@ -94,7 +94,7 @@ The accuracy obtained by the model on the validation set is mentioned above. The
 
 
 ## Training
-We used MXNet as framework with gluon APIs to perform training. View the [training notebook](train_squeezenet.ipynb) to understand details for parameters and network for each of the above variants of ResNet.
+We used MXNet as framework with gluon APIs to perform training. View the [training notebook](train_squeezenet.ipynb) to understand details for parameters and network for each of the above variants of SqueezeNet.
```
Comment (ankkhedia) [inline models/image_classification/squeezenet/README.md]: good catch!

**Comment by abhinavs95** [comment]
@lupesko Thanks for pointing it out.. added description for PR

File: models/face_recognition/ArcFace/mtcnn-model/det1.prototxt (hunk 5 above)
Comment (abhinavs95) [reply models/face_recognition/ArcFace/mtcnn-model/det1.prototxt]: will do

File: models/face_recognition/ArcFace/mtcnn-model/det1-symbol.json (hunk 4 above)
[the remark this answers is not in the document]
Comment (abhinavs95) [reply models/face_recognition/ArcFace/mtcnn-model/det1-symbol.json]: will do

File: models/face_recognition/ArcFace/README.md [hunk 10]
```diff
@@ -0,0 +1,78 @@
+# ArcFace
+
+## Description
+ArcFace is a CNN based model for face recognition which learns discriminative features of faces and produces embeddings for input face images. To enhance the discriminative power of softmax loss, a novel supervisor signal called additive angular margin (ArcFace) is used here as an additive term in the softmax loss. ArcFace can use a variety of CNN networks as its backend, each having different accuracy and performance.
```
Comment (aaronmarkham) [inline models/face_recognition/ArcFace/README.md]: Seems like this needs a reference

File: models/face_recognition/ArcFace/README.md [hunk 11]
```diff
@@ -0,0 +1,78 @@
+# ArcFace
+
+## Description
+ArcFace is a CNN based model for face recognition which learns discriminative features of faces and produces embeddings for input face images. To enhance the discriminative power of softmax loss, a novel supervisor signal called additive angular margin (ArcFace) is used here as an additive term in the softmax loss. ArcFace can use a variety of CNN networks as its backend, each having different accuracy and performance. 
+
+## Use cases
+For each face image, the model produces a fixed length embedding vector corresponding to the face in the image. The vectors from face images of a single person have a higher similarity than that from different persons. Therefore, the model is primarily used for face recognition/verification. It can also be used in other applications like facial feature based clustering.
```
Comment (aaronmarkham) [inline models/face_recognition/ArcFace/README.md]: Link to facial feature based clustering?

Comment (aaronmarkham) [inline models/face_recognition/ArcFace/README.md]: Example of the result?

File: models/face_recognition/ArcFace/README.md [hunk 12]
```diff
@@ -0,0 +1,78 @@
...
+
+## Model
+The model LResNet100E-IR is an ArcFace model that uses ResNet100 as a backend with modified input and output layers.
+
+|Model        |ONNX Model  |ONNX version| LFW accuracy (%)|CFP-FF accuracy (%)|CFP-FP accuracy (%)|AgeDB-30 accuracy (%)|
+|-------------|:--------------|:--------------|:--------------|:--------------|:--------------|:--------------|
+|LResNet100E-IR|    [248.9 MB](https://s3.amazonaws.com/onnx-model-zoo/arcface/resnet100/resnet100.onnx)|    1.2.1  |99.77     | 99.83  |  94.21     | 97.87|
+
+## Inference
+We used MXNet as framework to perform inference. View the notebook [arcface_inference](arcface_inference.ipynb) to understand how to use above models for doing inference. A brief description of the inference process is provided below:
```
Comment (aaronmarkham) [inline models/face_recognition/ArcFace/README.md]: : --> .

File: models/face_recognition/ArcFace/README.md [hunk 13]
```diff
@@ -0,0 +1,78 @@
...
+
+### Input 
+The input to the model should preferably be images containing a single face in each image. There are no constraints on the size of the image. The example displayed in the inference notebook was done using jpeg images.
```
Comment (aaronmarkham) [inline models/face_recognition/ArcFace/README.md]: Preferably? What happens if there are multiple faces? Does it just pick the most likely face and give you the result on that one?

File: models/face_recognition/ArcFace/README.md [hunk 14]
```diff
@@ -0,0 +1,78 @@
...
+
+* **Age Database (AgeDB)** is a dataset with large variations in pose, expression, illuminations, and age. AgeDB contains 12240 images of 440 distinct subjects, such as actors, actresses, writers, scientists, and politicians.  Each image is annotated with respect to the identity, age and gender attribute. The minimum and maximum ages are 3 and 101, respectively. The average age range for each subject is 49 years. There are four groups of test data with different year gaps (5, 10, 20 and 30 years respectively). The last subset, AgeDB-30 is used here as its the most challenging.
+
+### Setup
+1. Download the file  `faces_ms1m_112x112.zip` : [8.1 GB](https://s3.amazonaws.com/onnx-model-zoo/arcface/dataset/faces_ms1m_112x112.zip)
+2. Unzip `faces_ms1m_112x112.zip` to produce a folder of the same name. Use path to this folder in the notebooks. This folder contains the training as well as the validation datasets.
+
+## Validation
+The validation techniques for the three validation sets are described below:
+* **LFW** : Face verification accuracy on 6000 face pairs.
```
Comment (aaronmarkham) [inline models/face_recognition/ArcFace/README.md]: 6,000

**Comment by aaronmarkham** [comment]
I get an error running the inference notebook. And I'm also wondering why I need mxnet-cu90mkl for an inference demo. Can't run this on the Mac?

Here's the error... I think the dependencies list is missing stuff:

```
---> 16 from mtcnn_detector import MtcnnDetector
     17 from skimage import transform as trans
     18 import matplotlib.pyplot as plt

~/Development/abhinav-zoo/models/face_recognition/ArcFace/mtcnn_detector.py in <module>()
      7 from multiprocessing import Pool
      8 from itertools import repeat
----> 9 from itertools import izip
     10 from helper import nms, adjust_input, generate_bbox, detect_first_stage_warpper
     11 

ImportError: cannot import name 'izip'
```

**Comment by aaronmarkham** [comment]
The mtcnn part adds a lot of complexity and dependencies to the inference demo. All it is doing is face detection and cropping, but it dominates the code and discussion. 

My suggestion would be to abstract this away so that you can focus on the key part of this model: input faces, get the vecs, calc similarity. 

What if you use some REST API that will provide the cropped images for you, or at least coordinates and then you crop it yourself? Or I suppose you could move all of that code into a python file and don't include it in the inference notebook (though we still have a lot of extra unrelated dependencies).

**Comment by abhinavs95** [comment]
@aaronmarkham are you using python 3? The import izip error occurs in python 3. All the notebooks are prepared using python 2.. I'll mention this in the markdown at the start of each notebook.

**Comment by abhinavs95** [comment]
I agree that the face detection adds a lot of dependencies, but I've  used it because thats what is used in the paper and it performs well. 

Also, I want to have the preprocess function in the notebook instead of a script because that makes it more accessible to the user and preprocessing is an important part of the inference. I can dump the function in a script and call it from the notebook to clean things up a bit.

**Comment by simoncorstonoliver** [comment]
@abhinavs95 it's 2018. Let's make sure all notebooks work in Python 2.7+ and 3.6+

File: models/face_recognition/ArcFace/face_image.py [hunk 15]
```diff
@@ -0,0 +1,269 @@
+
+from easydict import EasyDict as edict
```
[the remark this answers is not in the document]
Comment (abhinavs95) [reply models/face_recognition/ArcFace/face_image.py]: Added comments in the file explaining each function

File: models/face_recognition/ArcFace/face_preprocess.py [hunk 16]
```diff
@@ -0,0 +1,113 @@
+
```
[the remark this answers is not in the document]
Comment (abhinavs95) [reply models/face_recognition/ArcFace/face_preprocess.py]: done.. added comments explaining each function

File: models/face_recognition/ArcFace/face_preprocess.py [hunk 17]
```diff
@@ -0,0 +1,113 @@
...
+
+    #print(src.shape, dst.shape)
+    #print(src)
+    #print(dst)
+    #print(M)
+    warped = cv2.warpAffine(img,M,(image_size[1],image_size[0]), borderValue = 0.0)
+
+    #tform3 = trans.ProjectiveTransform()
+    #tform3.estimate(src, dst)
```
[the remark this answers is not in the document]
Comment (abhinavs95) [reply models/face_recognition/ArcFace/face_preprocess.py]: thanks for pointing it out.. removed all unused code

File: models/face_recognition/ArcFace/fresnet.py [hunk 18]
```diff
@@ -0,0 +1,592 @@
...
+from __future__ import division
+from __future__ import print_function
+import mxnet as mx
+import numpy as np
+import symbol_utils
+import sklearn
+
+def Conv(**kwargs):
+    #name = kwargs.get('name')
+    #_weight = mx.symbol.Variable(name+'_weight')
```
[the remark this answers is not in the document]
Comment (abhinavs95) [reply models/face_recognition/ArcFace/fresnet.py]: done

File: models/face_recognition/ArcFace/image_iter.py [hunk 19]
```diff
@@ -0,0 +1,284 @@
+from __future__ import absolute_import
+from __future__ import division
+from __future__ import print_function
+
+import os
+import random
+import logging
+import sys
+import numbers
+import math
```
[the remark this answers is not in the document]
Comment (abhinavs95) [reply models/face_recognition/ArcFace/image_iter.py]: added comments explaining functions and classes in the file

File: models/face_recognition/ArcFace/mtcnn-model/det1-symbol.json (hunk 4 above)
[the remark this answers is not in the document]
Comment (abhinavs95) [reply models/face_recognition/ArcFace/mtcnn-model/det1-symbol.json]: moved all of the pre-trained face detector models in mtcnn-model folder to s3 with links to download in the notebooks

File: models/face_recognition/ArcFace/mtcnn-model/det1.prototxt (hunk 5 above)
Comment (abhinavs95) [reply models/face_recognition/ArcFace/mtcnn-model/det1.prototxt]: done

File: models/face_recognition/ArcFace/mtcnn-model/det2-symbol.json (hunk 6 above)
Comment (abhinavs95) [reply models/face_recognition/ArcFace/mtcnn-model/det2-symbol.json]: done

File: models/face_recognition/ArcFace/mtcnn-model/det2.prototxt (hunk 7 above)
Comment (abhinavs95) [reply models/face_recognition/ArcFace/mtcnn-model/det2.prototxt]: done

File: models/face_recognition/ArcFace/symbol_utils.py (hunk 8 above)
Comment (abhinavs95) [reply models/face_recognition/ArcFace/symbol_utils.py]: done

File: models/image_classification/squeezenet/README.md (hunk 9 above)
Comment (abhinavs95) [reply models/image_classification/squeezenet/README.md]: Thanks!

**Comment by abhinavs95** [comment]
@aaronmarkham The notebooks work on a Mac too. I have mentioned after `pip install mxnet-cu90mkl` that other versions can be used. mxnet-cu90mkl is just an example using which I prepared the notebooks.

 Also, I have moved all pre-trained models in the mtcnn-model folder to s3 with links in the notebook to access it. It reduces the clutter in the repository.

File: models/face_recognition/ArcFace/README.md (hunk 1 above)
Comment (abhinavs95) [reply models/face_recognition/ArcFace/README.md]: done!

File: models/face_recognition/ArcFace/README.md (hunk 3 above)
Comment (abhinavs95) [reply models/face_recognition/ArcFace/README.md]: done

File: models/face_recognition/ArcFace/README.md [hunk 20]
```diff
@@ -0,0 +1,68 @@
...
+
+* **CFP** : Two types of face verification - Frontal-Frontal (FF) and Frontal-Profile (FP), each having 10 folders with 350 same-person pairs and 350 different person pairs.
+
+* **AgeDB** : Validation is only performed on AgeDB-30 as mentioned above, with a metric same as LFW.
+
+The accuracy obtained by the model on the validation set is mentioned above and is within 1-2% of the original paper.
```
[the remark this answers is not in the document]
Comment (abhinavs95) [reply models/face_recognition/ArcFace/README.md]: done for ArcFace as well as the other models

File: models/face_recognition/ArcFace/README.md (hunk 2 above)
Comment (abhinavs95) [reply models/face_recognition/ArcFace/README.md]: Added footnote below table which links to the validation sets and methods section further down the page

**Comment by ankkhedia** [comment]
Approving changes and merging since it seems all the issues were addressed
